export class Clientes {

    constructor(
        public nombre: string,
        public apellido: string,
        public nombres: string,
        public tipodocumento: string,
        public identificacion: number,
        public fechanac: string,
        public email?: string,
        public telefono?: string,
        public telefonowhat?: string,  

        public empresa?: string,
        public cargo?: string,
        public direccioncasa?: string,
        public direcciontrabajo?: string,

        public referencia1?: string,
        public telreferencia1?: string,
        public referencia2?: string,
        public telreferencia2?: string,
        public referencia3?: string,
        public telreferencia3?: string,
             
        public imgdocfrontal?: string,
        public imgdocposterior?: string,
        public imgcartalab?: string,
        public imgservicios?: string,
        public imgcolilla?: string,
        public imgvideollamada?: string,


        public Estado?: string,
        public labelestado?: string,

        public cupo?: number,

        public valorprestamo?: number,
        public valortotal?: number,
        public direccion2?: string,
        public valorcuota?: number,
        public fechaultpago?: number,
        public empleado?: string,
        public empleadoold?: string,
        public fechainicio?: number,
        public fechafinal?: number,
        public numerocuotas?: number,
        public ruta?: number,
        public _id?: string,
        public cliente?: string,
        public date?: number,
        public AutorNombre?: string,
        public EstadoAutor?: string,
       
        public saldo?: number,
        public cuotaspend?: number,
        public numruta?: number,
        public calificacion?: number,
        public etmora?: string,
        public mora?: number,
        public picos?: number,
        public etpago?: boolean,
        public img?: string,
        public estadopres?: any,
        public cuentpag?: number,
        public cuentpend?: number,
        public latitud?: number,
        public longitud?: number,
        public renovacion?: boolean,
        public CobroMora?: number,
        public status?: string,
        public metadata?: boolean,
        public fechaformat?: string,
        public validado?: boolean,
        public ultcolor?: string,
        public morat?: number,
        public dipago?: string,
        public inforabono?: number,
        public iconrenovar?: boolean,
        public estadopag?: string,
        public infoarque?: string,
        public labelarque?: string,
        public inforabonoa?: number,
        public modalidad?: string,
        public novabono?: boolean,
        public empleoldnombre?: string,
       
        public pais?: string,
        public oficina?: string,
        public asesoremail?: string,
        public totalcreditos?: number,
        public Direcciones?: any,
        public morasig?: number,
        public version?: string,
        public isSelected?: boolean,
        public observacion?: string,

        public statuspres?: string,
    ) { }
}
